routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');

});

    Route::resource('administrator', 'administratorsController');

    Route::resource('mahasiswa_calons', 'mahasiswa_calonController');
    Route::get('mahasiswa_calon/',['as' => 'mahasiswa_calon', 'uses' => 'mahasiswa_calonController@index']);
    Route::get('mahasiswa_calonCreate/',['as' => 'mahasiswa_calonCreate', 'uses' => 'mahasiswa_calonController@create']);
    //Route::get('get-mahasiswa_calon','mahasiswa_calonController@getmahasiswa_calon');
    

    Route::resource('majors', 'major\majorController');
    Route::get('majorsIndex/',['as' => 'majorsIndex', 'uses' => 'major\majorController@index']);
    Route::get('majorsCreate/',['as' => 'majorsCreate', 'uses' => 'major\majorController@create']);

    Route::resource('faculties', 'faculties\facultiesController');
    Route::get('facultiesIndex/',['as' => 'facultiesIndex', 'uses' => 'faculties\facultiesController@index']);
    Route::get('facultiesCreate/',['as' => 'facultiesCreate', 'uses' => 'faculties\facultiesController@create']);

    Route::resource('departments', 'departments\departmentsController');
    Route::get('departmentsIndex/',['as' => 'departmentsIndex', 'uses' => 'departments\departmentsController@index']);
    Route::get('departmentsCreate/',['as' => 'departmentsCreate', 'uses' => 'departments\departmentsController@create']);

    Route::get('academic_years/',['as' => 'academic_years', 'uses' => 'academic_yearsController@index']);
    Route::get('get-academic_years','academic_yearsController@getacademic_years');

    Route::get('administrators/',['as' => 'administrators', 'uses' => 'administratorsController@index']);
    Route::get('get-administratorsView','administratorsController@getadministrators');
    Route::get('get-administratorsCreate','administratorsController@create');
    Route::get('administratorsCreate/',['as' => 'administratorsCreate', 'uses' => 'administratorsController@create']);
    Route::get('administratorsStore/',['as' => 'administratorsStore', 'uses' => 'administratorsController@store']);

app/department.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class department extends Model
{
    protected $table = 'departments';
}

app/Http/Controllers/departments/departmentsController.php
<?php

namespace App\Http\Controllers\departments;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\department;
use App\kota_kabupaten;
use App\faculties;
use App\User;

class departmentsController extends Controller
{
    public function index()
    {   
    	
    	$departments=department::all();
        return view('departments.departmentsView',compact('departments'));
    }
    public function create()
    {
    	$users=User::all();
        $kota_kabupaten=kota_kabupaten::all();
    	$faculties=faculties::all();
        return view('departments.departmentsCreate',compact('faculties','kota_kabupaten','users'));
    }
    public function store(Request $request)
    {
        $departments = new department();
        $departments->faculty_id=$request->faculty_id;
        $departments->name=$request->name;
        $departments->telp=$request->telp;
        $departments->email=$request->email;
        $departments->address=$request->address;
        $departments->facsimile=$request->facsimile;
        $departments->homepage=$request->homepage;
        $departments->faculty_name=$request->faculty_name;
        $departments->university=$request->university;
        $departments->city=$request->city;
        $departments->user_id=$request->user_id;
        $departments->save();
        return redirect()->route('departments.index')->with('alert-success','Data berhasil Disimpan.');
    }
    public function edit($id)
    {
        $users=User::all();
        $departments = department::findOrFail($id);
        $kota_kabupaten=kota_kabupaten::all();
    	$faculties=faculties::all();
        return view('departments.departmentsEdit',compact('faculties','kota_kabupaten','users','departments'));
    }
    public function update(Request $request, $id)
    {
        $departments = department::findOrFail($id);
        $departments->faculty_id=$request->faculty_id;
        $departments->name=$request->name;
        $departments->telp=$request->telp;
        $departments->email=$request->email;
        $departments->address=$request->address;
        $departments->facsimile=$request->facsimile;
        $departments->homepage=$request->homepage;
        $departments->faculty_name=$request->faculty_name;
        $departments->university=$request->university;
        $departments->city=$request->city;
        $departments->user_id=$request->user_id;
        $departments->save();
        return redirect()->route('departments.index')->with('alert-success', 'Data Successfully Updated.');
    }
    public function destroy($id)
    {
        $departments = department::findOrFail($id);
        $departments->delete();
        return redirect()->route('departments.index')->with('alert-success', 'Data Berhasil Dihapus.');
    }
}

resources/views/departments/departmentsCreate.blade.php
@extends('index')

@section('content')
<div class="container-fluid">
    
                <div class="panel-body">
                <br style="clear:both">
                    <h4 class="w3-label w3-text-green" style="margin-bottom: 25px; text-align: center;"><b>Tambah Department</b></h4>
                    <hr>
            <form action="{{route('departments.store')}}" method="post">
                    {{csrf_field()}}
                        <label class="w3-label w3-text-green"><b>Faculty ID</b></label>
                        <div class="form-group{{ $errors->has('faculty_id') ? ' has-error' : '' }}">
                            <select class="form-control m-bot15" name="faculty_id">
                            @if($faculties->count() > 0)
                            @foreach($faculties as $data)
                            <option value="{{$data->id}}">{{$data->name}}</option>
                            @endForeach
                            @else
                            No Record Found
                            @endif   
                        </select>
                        
                            {!! $errors->first('faculty_id', '<p class="help-block">:message</p>') !!}
                        </div>
                        <label class="w3-label w3-text-green"><b>Name</b></label>
                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <input type="text" name="name" class="form-control" placeholder="name" required>
                        
                            {!! $errors->first('name', '<p class="help-block">:message</p>') !!}
                        </div>
                        <label class="w3-label w3-text-green"><b>Telp</b></label>
                            <div class="form-group{{ $errors->has('telp') ? ' has-error' : '' }}">
                            <input type="telp" name="telp" class="form-control" placeholder="telp" required>
                        
                            {!! $errors->first('telp', '<p class="help-block">:message</p>') !!}
                        </div>
                        
                        <label class="w3-label w3-text-green"><b>Email</b></label>
                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <input type="email" name="email" class="form-control" placeholder="email" required>
                        
                            {!! $errors->first('email', '<p class="help-block">:message</p>') !!}
                        </div>
                        <label class="w3-label w3-text-green"><b>Address</b></label>
                        <div class="form-group{{ $errors->has('address') ? ' has-error' : '' }}">
                            <input type="text" name="address" class="form-control" placeholder="address" required>
                        
                            {!! $errors->first('address', '<p class="help-block">:message</p>') !!}
                        </div>
                        <label class="w3-label w3-text-green"><b>Facsimile</b></label>
                        <div class="form-group{{ $errors->has('facsimile') ? ' has-error' : '' }}">
                            <input type="text" name="facsimile" class="form-control" placeholder="facsimile" required>
                        
                            {!! $errors->first('facsimile', '<p class="help-block">:message</p>') !!}
                        </div>
                        <label class="w3-label w3-text-green"><b>Homepage</b></label>
                        <div class="form-group{{ $errors->has('homepage') ? ' has-error' : '' }}">
                            <input type="text" name="homepage" class="form-control" placeholder="homepage" required>
                        
                            {!! $errors->first('homepage', '<p class="help-block">:message</p>') !!}
                        </div>
                        <label class="w3-label w3-text-green"><b>Faculty Name</b></label>
                        <div class="form-group{{ $errors->has('faculty_name') ? ' has-error' : '' }}">
                            <input type="text" name="faculty_name" class="form-control" placeholder="faculty_name" required>
                        
                            {!! $errors->first('faculty_name', '<p class="help-block">:message</p>') !!}
                        </div>
                        <label class="w3-label w3-text-green"><b>University</b></label>
                        <div class="form-group{{ $errors->has('university') ? ' has-error' : '' }}">
                            <input type="text" name="university" class="form-control" placeholder="university" required>
                        
                            {!! $errors->first('university', '<p class="help-block">:message</p>') !!}
                        </div>
                        <label class="w3-label w3-text-green"><b>City</b></label>
                        <div class="form-group{{ $errors->has('city') ? ' has-error' : '' }}">
                            <select class="form-control m-bot15" name="city">
                            @if($kota_kabupaten->count() > 0)
                            @foreach($kota_kabupaten as $data)
                            <option value="{{$data->id}}">{{$data->nama_kota_kabupaten}}</option>
                            @endForeach
                            @else
                            No Record Found
                            @endif   
                        </select>
                        
                            {!! $errors->first('city', '<p class="help-block">:message</p>') !!}
                        </div>
                        <label class="w3-label w3-text-green"><b>User ID</b></label>
                        <div class="form-group{{ $errors->has('user_id') ? ' has-error' : '' }}">
                            <select class="form-control m-bot15" name="user_id">
                            @if($users->count() > 0)
                            @foreach($users as $data)
                            <option value="{{$data->id}}">{{$data->name}}</option>
                            @endForeach
                            @else
                            No Record Found
                            @endif   
                        </select>
                        
                            {!! $errors->first('user_id', '<p class="help-block">:message</p>') !!}
                        </div>
                            <input type="submit" class="btn btn-primary" value="Simpan">
                       

                    </form>
         </div>
     </div>

        <!-- /.content -->
    </section>
    <!-- /.main-section -->
@endsection

resources/views/departments/departmentsEdit.blade.php
@extends('index')
@section('content')
<div class="container-fluid">
	
				<div class="panel-body">
				<br style="clear:both">
					<h4 class="w3-label w3-text-green" style="margin-bottom: 25px; text-align: center;"><b>EDIT JOBLIST</b></h4>
                    <hr>
					<form action="{{route('departments.update',$departments->id)}}" method="post">
					<input name="_method" type="hidden" value="PATCH">
					{{csrf_field()}}
						<label class="w3-label w3-text-green"><b>Facilty ID</b></label>
						<div class="form-group{{ $errors->has('faculty_id') ? ' has-error' : '' }}">
							<select class="form-control m-bot15" name="faculty_id">
                            @foreach($faculties as $data)
                            <option 
                            value="{{$data->id}}"
                            @if($data->id === $departments->faculty_id)
                            selected
                            @endif
                            >
                            {{$data->name}}
                        </option>
                            @endForeach
                           
                        </select>
							{!! $errors->first('faculty_id', '<p class="help-block">:message</p>') !!}
						</div>
						<label class="w3-label w3-text-green"><b>Name</b></label>
						<div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
							<input type="text" name="name" class="form-control" placeholder="name" value="{{$departments->name}}" required>
							{!! $errors->first('name', '<p class="help-block">:message</p>') !!}
						</div>
						<label class="w3-label w3-text-green"><b>Telp</b></label>
						<div class="form-group{{ $errors->has('telp') ? ' has-error' : '' }}">
							<input type="text" name="telp" class="form-control" placeholder="Telp" value="{{$departments->telp}}" required>
							{!! $errors->first('telp', '<p class="help-block">:message</p>') !!}
						</div>
						<label class="w3-label w3-text-green"><b>Email</b></label>
						<div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
							<input type="email" name="email" class="form-control" placeholder="Email" value="{{$departments->email}}" required>
							{!! $errors->first('email', '<p class="help-block">:message</p>') !!}
						</div>
						<label class="w3-label w3-text-green"><b>Address</b></label>
						<div class="form-group{{ $errors->has('address') ? ' has-error' : '' }}">
							<input type="date" name="address" class="form-control" placeholder="Address" value="{{$departments->address}}" required>
							{!! $errors->first('address', '<p class="help-block">:message</p>') !!}
						</div>
						<label class="w3-label w3-text-green"><b>Facimile</b></label>
						<div class="form-group{{ $errors->has('facimile') ? ' has-error' : '' }}">
							<input type="date" name="facimile" class="form-control" placeholder="Facimile" value="{{$departments->facimile}}" required>
							{!! $errors->first('address', '<p class="help-block">:message</p>') !!}
						</div>
						<label class="w3-label w3-text-green"><b>Homepage</b></label>
						<div class="form-group{{ $errors->has('homepage') ? ' has-error' : '' }}">
							<input type="date" name="homepage" class="form-control" placeholder="Homepage" value="{{$departments->homepage}}" required>
							{!! $errors->first('homepage', '<p class="help-block">:message</p>') !!}
						</div>
						<label class="w3-label w3-text-green"><b>Homepage</b></label>
						<div class="form-group{{ $errors->has('homepage') ? ' has-error' : '' }}">
							<input type="date" name="homepage" class="form-control" placeholder="Homepage" value="{{$departments->homepage}}" required>
							{!! $errors->first('homepage', '<p class="help-block">:message</p>') !!}
						</div>
						
						
						<div class="form-group">
							<button type="submit" class="btn button btn-primary pull-right"><span class="glyphicon glyphicon-pencil">Edit</span></button>

							<a href="{{route('faculties.index')}}" class="btn button  btn-primary pull-left"><span class="glyphicon glyphicon-arrow-left"></span></a>
						</div>
					</form>
				
		
	</div>
</div>
@endsection

resources/views/departments/departmentsView.blade.php
@extends('index')
 
@section('content')
<div class="row">
<div class="col-md-8 col-md-offset-2">
    <h3 align="center">Data Calon Department</h3>   
    <a href="{{route('departmentsCreate')}}" class="btn btn-primary btn-md" ><span  class="glyphicon glyphicon-list-alt"></span>  Add New</a></a>  
    <div>
        <h3> </h3>
    </div>
    <table class="table table-striped" id="table">
        <thead>
            <tr>
                <td>No</td>
                <td>Fakultas ID</td>
                <td>Name</td>
                <td>Telp</td>
                <td>Email</td>
                <td>Address</td>
                <td>Nama Fakultas</td>
                <td>University</td>
                <td>City</td>
                <td>User ID</td>
                <td>Aksi</td>
                
            </tr>
        </thead>
        <tbody>
            <?php $no=1; ?>
                        @foreach($departments as $data)
                            <tr class="">
                            <td>{{$no++}}</td>
                            <td>{{$data->faculty_id}}</td>
                            <td>{{$data->name}}</td>
                            <td>{{$data->telp}}</td> 
                            <td>{{$data->email}}</td>
                            <td>{{$data->address}}</td>  
                            <td>{{$data->facsimile}}</td>
                            <td>{{$data->homepage}}</td>
                            <td>{{$data->faculty_name}}</td>
                            <td>{{$data->university}}</td>
                            <td>{{$data->city}}</td>  
                            <td>{{$data->user_id}}</td> 
                            <td><form method="POST" action="{{ route('departments.destroy', $data->id) }}" accept-charset="UTF-8">
                                <input name="_method" type="hidden" value="DELETE">
                                <input name="_token" type="hidden" value="{{ csrf_token() }}">

                                <a href="{{ route('departments.edit', $data->id) }}" class="btn btn-primary btn-xs" data-toggle="tooltip" data-placement="bottom" title="edit"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>


                                <button type="submit" class="btn btn-primary btn-xs" data-toggle="tooltip" data-placement="bottom" title="delete"><span class="glyphicon glyphicon-trash" onclick="return confirm('Anda yakin akan menghapus data ?');" ></span>
                                    </button>
                                </form>
                            </td>
                            </tr>
                            @endforeach
        </tbody>
    </table>
</div>
</div>
@endsection