routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');

});

    Route::resource('administrator', 'administratorsController');

    Route::resource('mahasiswa_calons', 'mahasiswa_calonController');
    Route::get('mahasiswa_calon/',['as' => 'mahasiswa_calon', 'uses' => 'mahasiswa_calonController@index']);
    Route::get('mahasiswa_calonCreate/',['as' => 'mahasiswa_calonCreate', 'uses' => 'mahasiswa_calonController@create']);
    //Route::get('get-mahasiswa_calon','mahasiswa_calonController@getmahasiswa_calon');
    

    Route::resource('majors', 'major\majorController');
    Route::get('majorsIndex/',['as' => 'majorsIndex', 'uses' => 'major\majorController@index']);
    Route::get('majorsCreate/',['as' => 'majorsCreate', 'uses' => 'major\majorController@create']);

    Route::resource('faculties', 'faculties\facultiesController');
    Route::get('facultiesIndex/',['as' => 'facultiesIndex', 'uses' => 'faculties\facultiesController@index']);
    Route::get('facultiesCreate/',['as' => 'facultiesCreate', 'uses' => 'faculties\facultiesController@create']);

    Route::resource('departments', 'departments\departmentsController');
    Route::get('departmentsIndex/',['as' => 'departmentsIndex', 'uses' => 'departments\departmentsController@index']);
    Route::get('departmentsCreate/',['as' => 'departmentsCreate', 'uses' => 'departments\departmentsController@create']);

    Route::get('academic_years/',['as' => 'academic_years', 'uses' => 'academic_yearsController@index']);
    Route::get('get-academic_years','academic_yearsController@getacademic_years');

    Route::get('administrators/',['as' => 'administrators', 'uses' => 'administratorsController@index']);
    Route::get('get-administratorsView','administratorsController@getadministrators');
    Route::get('get-administratorsCreate','administratorsController@create');
    Route::get('administratorsCreate/',['as' => 'administratorsCreate', 'uses' => 'administratorsController@create']);
    Route::get('administratorsStore/',['as' => 'administratorsStore', 'uses' => 'administratorsController@store']);

app/mahasiswa_calon.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class mahasiswa_calon extends Model
{
    protected $table = 'mahasiswa_calon';

}

app/Http/Controllers/mahasiswa_calonController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\mahasiswa_calon;
use App\Http\Requests;
use App\majors;
use App\academic_years;
use App\kota_kabupaten;
use App\Http\Requests\mahasiswa_calon\UpdateRequest;
use App\Http\Requests\mahasiswa_calon\StoreRequest;
use Datatables;

class mahasiswa_calonController extends Controller
{
    public function index()
    {   
        
    	$mahasiswa_calon=mahasiswa_calon::all();
        return view('mahasiswa_calon.mahasiswa_calonView',compact('mahasiswa_calon'));
    }

    public function getmahasiswa_calon()
    {
        $mahasiswa_calon = mahasiswa_calon::select(['program_studi_id','tahun_ajaran_id','nama','telp','email','tempat_lahir','gender','alamat_asal','jalur_pendaftaran','reguler','hasil_seleksi'])->get();
  
        return Datatables::of($mahasiswa_calon)->make(true);
    }
    public function create()
    {
        $majors=majors::all();
        $kota_kabupaten=kota_kabupaten::all();
        $academics=academic_years::all();
        return view('mahasiswa_calon.mahasiswa_calonCreate',compact('kota_kabupaten','academics','majors'));
        //
    }
    public function store(StoreRequest $request)
    {
        $mahasiswa_calon = new mahasiswa_calon();
        $mahasiswa_calon->program_studi_id = $request->program_studi_id;
        $mahasiswa_calon->tahun_ajaran_id=$request->tahun_ajaran_id;
        $mahasiswa_calon->nama=$request->nama;
        $mahasiswa_calon->telp=$request->telp;
        $mahasiswa_calon->email=$request->email;
        $mahasiswa_calon->tempat_lahir=$request->tempat_lahir;
        $mahasiswa_calon->gender=$request->gender;
        $mahasiswa_calon->alamat_asal=$request->alamat_asal;
        $mahasiswa_calon->jalur_pendaftaran=$request->jalur_pendaftaran;
        $mahasiswa_calon->reguler=$request->reguler;
        $mahasiswa_calon->hasil_seleksi=$request->hasil_seleksi;
        $mahasiswa_calon->save();
        return redirect()->route('mahasiswa_calons.index')->with('alert-success','Data berhasil Disimpan.');
    }
    public function destroy($id)
    {
        $mahasiswa_calon = mahasiswa_calon::findOrFail($id);
        $mahasiswa_calon->delete();
        return redirect()->route('mahasiswa_calons.index')->with('alert-success', 'Data Berhasil Dihapus.');
    }
    public function edit($id)
    {
        $majors=majors::all();
        $academics=academic_years::all();
        $kota_kabupaten=kota_kabupaten::all();
        $mahasiswa_calon = mahasiswa_calon::findOrFail($id);
        return view('mahasiswa_calon.mahasiswa_calonEdit', compact('academics','kota_kabupaten','majors','mahasiswa_calon'));
    }
    public function update(UpdateRequest $request, $id)
    {
        $mahasiswa_calon = mahasiswa_calon::findOrFail($id);
        $mahasiswa_calon->program_studi_id = $request->program_studi_id;
        $mahasiswa_calon->tahun_ajaran_id=$request->tahun_ajaran_id;
        $mahasiswa_calon->nama=$request->nama;
        $mahasiswa_calon->telp=$request->telp;
        $mahasiswa_calon->email=$request->email;
        $mahasiswa_calon->tempat_lahir=$request->tempat_lahir;
        $mahasiswa_calon->gender=$request->gender;
        $mahasiswa_calon->alamat_asal=$request->alamat_asal;
        $mahasiswa_calon->jalur_pendaftaran=$request->jalur_pendaftaran;
        $mahasiswa_calon->reguler=$request->reguler;
        $mahasiswa_calon->hasil_seleksi=$request->hasil_seleksi;
        $mahasiswa_calon->save();
        return redirect()->route('mahasiswa_calons.index')->with('alert-success', 'Data Successfully Updated.');
    }
}

resources/views/mahasiswa_calon/mahasiswa_calonCreate.blade.php
@extends('index')

@section('content')
<div class="container-fluid">
    
                <div class="panel-body">
                <br style="clear:both">
                    <h4 class="w3-label w3-text-green" style="margin-bottom: 25px; text-align: center;"><b>Tambah Mahasiwa</b></h4>
                    <hr>
            <form action="{{route('mahasiswa_calons.store')}}" method="post">
                    {{csrf_field()}}
                    <label class="w3-label w3-text-green"><b>Program Studi ID</b></label>
                        <div class="form-group{{ $errors->has('program_studi_id') ? ' has-error' : '' }}">
                        <select class="form-control m-bot15" name="program_studi_id">
                            @if($majors->count() > 0)
                            @foreach($majors as $major)
                            <option value="{{$major->id}}">{{$major->name}}</option>
                            @endForeach
                            @else
                            No Record Found
                            @endif   
                        </select>
                    </div>
                    <label class="w3-label w3-text-green"><b>Tahun Ajaran ID</b></label>
                        <div class="form-group{{ $errors->has('tahun_ajaran_id') ? ' has-error' : '' }}">
                           <!-- <input type="text" name="tahun_ajaran_id" class="form-control" placeholder="tahun_ajaran_id" required>
                            {!! $errors->first('tahun_ajaran_id', '<p class="help-block">:message</p>') !!}-->
                            <select class="form-control m-bot15" name="tahun_ajaran_id">
                            @if($academics->count() > 0)
                            @foreach($academics as $major)
                            <option value="{{$major->id}}">{{$major->name}}</option>
                            @endForeach
                            @else
                            No Record Found
                            @endif   
                        </select>
                        </div>
                        <label class="w3-label w3-text-green"><b>nama</b></label>
                        <div class="form-group{{ $errors->has('nama') ? ' has-error' : '' }}">
                            <input type="text" name="nama" class="form-control" placeholder="nama" required>
                        
                            {!! $errors->first('nama', '<p class="help-block">:message</p>') !!}
                        </div>
                        <label class="w3-label w3-text-green"><b>Telp</b></label>
                        <div class="form-group{{ $errors->has('telp') ? ' has-error' : '' }}">
                            <input type="text" name="telp" class="form-control" placeholder="telp" required>
                        
                            {!! $errors->first('telp', '<p class="help-block">:message</p>') !!}
                        </div>
                        <label class="w3-label w3-text-green"><b>Email</b></label>
                            <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <input type="email" name="email" class="form-control" placeholder="email" required>
                        
                            {!! $errors->first('email', '<p class="help-block">:message</p>') !!}
                        </div>
                        <label class="w3-label w3-text-green"><b>Tempat Lahir</b></label>
                        <div class="form-group{{ $errors->has('tempat_lahir') ? ' has-error' : '' }}">
                            <select class="form-control m-bot15" name="tempat_lahir">
                            @if($kota_kabupaten->count() > 0)
                            @foreach($kota_kabupaten as $kota)
                            <option value="{{$kota->id}}">{{$kota->nama_kota_kabupaten}}</option>
                            @endForeach
                            @else
                            No Record Found
                            @endif   
                        </select>
                        </div>
                        <label class="w3-label w3-text-green"><b>Gender</b></label>
                        <div class="form-group{{ $errors->has('gender') ? ' has-error' : '' }}">
                            <input type="text" name="gender" class="form-control" placeholder="gender" required>
                        
                            {!! $errors->first('gender', '<p class="help-block">:message</p>') !!}
                        </div>
                        <label class="w3-label w3-text-green"><b>Alamat Asal</b></label>
                        <div class="form-group{{ $errors->has('alamat_asal') ? ' has-error' : '' }}">
                            <input type="text" name="alamat_asal" class="form-control" placeholder="alamat_asal" required>
                        
                            {!! $errors->first('alamat_asal', '<p class="help-block">:message</p>') !!}
                        </div>
                        <label class="w3-label w3-text-green"><b>Jalur Pendaftaran</b></label>
                        <div class="form-group{{ $errors->has('jalur_pendaftaran') ? ' has-error' : '' }}">
                            <input type="text" name="jalur_pendaftaran" class="form-control" placeholder="jalur_pendaftaran" required>
                        
                            {!! $errors->first('jalur_pendaftaran', '<p class="help-block">:message</p>') !!}
                        </div>
                        <label class="w3-label w3-text-green"><b>Reguler</b></label>
                        <div class="form-group{{ $errors->has('reguler') ? ' has-error' : '' }}">
                            <input type="text" name="reguler" class="form-control" placeholder="reguler" required>
                        
                            {!! $errors->first('reguler', '<p class="help-block">:message</p>') !!}
                        </div>
                        <label class="w3-label w3-text-green"><b>Hasil Seleksi</b></label>
                        <div class="form-group{{ $errors->has('hasil_seleksi') ? ' has-error' : '' }}">
                            <input type="text" name="hasil_seleksi" class="form-control" placeholder="hasil_seleksis" required>
                        
                            {!! $errors->first('hasil_seleksi', '<p class="help-block">:message</p>') !!}
                        </div>
                            <input type="submit" class="btn btn-primary" value="Simpan">
                    

                    </form>
        </div>
    </div>
       
@endsection

resources/views/mahasiswa_calon/mahasiswa_calonEdit.blade.php
@extends('index')
@section('content')
<div class="container-fluid">
	
				<div class="panel-body">
				<br style="clear:both">
					<h4 class="w3-label w3-text-green" style="margin-bottom: 25px; text-align: center;"><b>EDIT JOBLIST</b></h4>
                    <hr>
					<form action="{{route('mahasiswa_calons.update', $mahasiswa_calon->id)}}" method="post">
					<input name="_method" type="hidden" value="PATCH">
					{{csrf_field()}}
						<label class="w3-label w3-text-green"><b>Program Studi ID</b></label>
						<div class="form-group{{ $errors->has('program_studi_id') ? ' has-error' : '' }}">
							
					<select class="form-control m-bot15" name="program_studi_id">
                            @foreach($majors as $major)
                            <option 
                            value="{{$major->id}}"
                            @if($major->id === $mahasiswa_calon->program_studi_id)
                            selected
                            @endif
                            >
                            {{$major->name}}
                        </option>
                            @endForeach
                           
                        </select>

						</div>

						<label class="w3-label w3-text-green"><b>Tahun Ajaran ID</b></label>
						<div class="form-group{{ $errors->has('tahun_ajaran_id') ? ' has-error' : '' }}">
							<select class="form-control m-bot15" name="tahun_ajaran_id">
                            @foreach($academics as $major)
                            <option 
                            value="{{$major->id}}"
                            @if($major->id === $mahasiswa_calon->tahun_ajaran_id)
                            selected
                            @endif
                            >
                            {{$major->name}}
                        </option>
                            @endForeach
                           
                        </select>
							{!! $errors->first('tahun_ajaran_id', '<p class="help-block">:message</p>') !!}
						</div>

						<label class="w3-label w3-text-green"><b>Nama</b></label>
						<div class="form-group{{ $errors->has('nama') ? ' has-error' : '' }}">
							<input type="text" name="nama" class="form-control" placeholder="nama" value="{{$mahasiswa_calon->nama}}" required>
							{!! $errors->first('nama', '<p class="help-block">:message</p>') !!}
						</div>

						<label class="w3-label w3-text-green"><b>Telp</b></label>
						<div class="form-group{{ $errors->has('telp') ? ' has-error' : '' }}">
							<input type="text" name="telp" class="form-control" placeholder="Telp" value="{{$mahasiswa_calon->telp}}" required>
							{!! $errors->first('telp', '<p class="help-block">:message</p>') !!}
						</div>
						<label class="w3-label w3-text-green"><b>Email</b></label>
						<div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
							<input type="email" name="email" class="form-control" placeholder="Email" value="{{$mahasiswa_calon->email}}" required>
							{!! $errors->first('email', '<p class="help-block">:message</p>') !!}
						</div>
						<label class="w3-label w3-text-green"><b>Tempat Lahir</b></label>
						<div class="form-group{{ $errors->has('tempat_lahir') ? ' has-error' : '' }}">
							<select class="form-control m-bot15" name="tempat_lahir">
                            @foreach($kota_kabupaten as $major)
                            <option 
                            value="{{$major->id}}"
                            @if($major->id === $mahasiswa_calon->tempat_lahir)
                            selected
                            @endif
                            >
                            {{$major->nama_kota_kabupaten}}
                        </option>
                            @endForeach
                           
                        </select>
							{!! $errors->first('tempat_lahir', '<p class="help-block">:message</p>') !!}
						</div>
						<label class="w3-label w3-text-green"><b>Gender</b></label>
						<div class="form-group{{ $errors->has('gender') ? ' has-error' : '' }}">
							<input type="text" name="gender" class="form-control" placeholder="Gender" value="{{$mahasiswa_calon->gender}}" required>
							{!! $errors->first('gender', '<p class="help-block">:message</p>') !!}
						</div>
						<label class="w3-label w3-text-green"><b>Alamat Asal</b></label>
						<div class="form-group{{ $errors->has('alamat_asal') ? ' has-error' : '' }}">
							<input type="text" name="alamat_asal" class="form-control" placeholder="Alamat Asal" value="{{$mahasiswa_calon->alamat_asal}}" required>
							{!! $errors->first('alamat_asal', '<p class="help-block">:message</p>') !!}
						</div>
						<label class="w3-label w3-text-green"><b>Jalur Pendaftaran</b></label>
						<div class="form-group{{ $errors->has('jalur_pendaftaran') ? ' has-error' : '' }}">
							<input type="text" name="jalur_pendaftaran" class="form-control" placeholder="Jalur Pendaftaran" value="{{$mahasiswa_calon->jalur_pendaftaran}}" required>
							{!! $errors->first('jalur_pendaftaran', '<p class="help-block">:message</p>') !!}
						</div>
						<label class="w3-label w3-text-green"><b>Reguler</b></label>
						<div class="form-group{{ $errors->has('reguler') ? ' has-error' : '' }}">
							<input type="text" name="reguler" class="form-control" placeholder="Reguler" value="{{$mahasiswa_calon->reguler}}" required>
							{!! $errors->first('reguler', '<p class="help-block">:message</p>') !!}
						</div>
						<label class="w3-label w3-text-green"><b>Hasil Seleksi</b></label>
						<div class="form-group{{ $errors->has('hasil_seleksi') ? ' has-error' : '' }}">
							<input type="text" name="hasil_seleksi" class="form-control" placeholder="Hasil Seleksi" value="{{$mahasiswa_calon->hasil_seleksi}}" required>
							{!! $errors->first('hasil_seleksi', '<p class="help-block">:message</p>') !!}
						</div>
						<div class="form-group">
							<button type="submit" class="btn button btn-primary pull-right"><span class="glyphicon glyphicon-pencil">Edit</span></button>

							<a href="{{route('mahasiswa_calons.index')}}" class="btn button  btn-primary pull-left"><span class="glyphicon glyphicon-arrow-left"></span></a>
						</div>
					</form>
				
		
	</div>
</div>
@endsection

resources/views/mahasiswa_calon/mahasiswa_calonView.blade.php
@extends('index')
 
@section('content')
<div class="row">
<div class="col-md-8 col-md-offset-2">
    <h3 align="center">Data Calon Mahasiswa </h3>   
    <a href="{{route('mahasiswa_calonCreate')}}" class="btn btn-primary btn-md" ><span  class="glyphicon glyphicon-list-alt"></span>  Add New</a></a>  
    <div>
        <h3> </h3>
    </div>
    <table class="table table-striped" id="table">
        <thead>
            <tr>
                <td>No</td>
                <td>Program Studi</td>
                <td>Tahun Ajaran</td>
                <td>Nama</td>
                <td>Telp</td>
                <td>Email</td>
                <td>Tempat Lahir</td>
                <td>Gender</td>
                <td>Alamat Asal</td>
                <td>Jalur Pendaftaran</td>
                <td>Reguler</td>
                <td>Hasil Seleksi</td>
                <td>Aksi</td>
                
            </tr>
        </thead>
        <tbody>
            <?php $no=1; ?>
                        @foreach($mahasiswa_calon as $mahasiswa_calon)
                            <tr class="">
                            <td>{{$no++}}</td>
                            <td>{{$mahasiswa_calon->program_studi_id}}</td>
                            <td>{{$mahasiswa_calon->tahun_ajaran_id}}</td>
                            <td>{{$mahasiswa_calon->nama}}</td>
                            <td>{{$mahasiswa_calon->telp}}</td>
                            <td>{{$mahasiswa_calon->email}}</td> 
                            <td>{{$mahasiswa_calon->tempat_lahir}}</td>
                            <td>{{$mahasiswa_calon->gender}}</td>  
                            <td>{{$mahasiswa_calon->alamat_asal}}</td>
                            <td>{{$mahasiswa_calon->jalur_pendaftaran}}</td> 
                            <td>{{$mahasiswa_calon->reguler}}</td> 
                            <td>{{$mahasiswa_calon->hasil_seleksi}}</td>   
                            <td><form method="POST" action="{{ route('mahasiswa_calons.destroy', $mahasiswa_calon->id) }}" accept-charset="UTF-8">
                                <input name="_method" type="hidden" value="DELETE">
                                <input name="_token" type="hidden" value="{{ csrf_token() }}">

                                <a href="{{route('mahasiswa_calons.edit', $mahasiswa_calon->id)}}" class="btn btn-primary btn-xs" data-toggle="tooltip" data-placement="bottom" title="edit"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>

                                <button type="submit" class="btn btn-primary btn-xs" data-toggle="tooltip" data-placement="bottom" title="delete"><span class="glyphicon glyphicon-trash" onclick="return confirm('Anda yakin akan menghapus data ?');" ></span>
                                    </button>
                                </form>
                            </td>
                            </tr>
                            @endforeach
        </tbody>
    </table>
</div>
</div>
@endsection
<!--@push('js')
@section('scripts') 
<script type="text/javascript">
  $(document).ready(function() {
    $('#table').DataTable(
        {
         "scrollX": true,
             processing: true,
                serverSide: true,
                //
                ajax: '{{ url("get-mahasiswa_calon") }}',   
        });
} );
 </script>

@endsection
@endpush
 
<!--@push('js')
<script type="text/javascript">
    $(function(){
        $("#data-mahasiswa_calon").DataTable({
            "scrollX": true,
             processing: true,
                serverSide: true,
                //
                ajax: '{{ url("get-mahasiswa_calon") }}',
                columns: [
                    { data: 'program_studi_id', name: 'program_studi_id' },
                    { data: 'tahun_ajaran_id', name: 'tahun_ajaran_id' },
                    { data: 'nama', name: 'nama' },
                    { data: 'telp', name: 'telp' },
                    { data: 'email', name: 'email' },
                    { data: 'tempat_lahir', name: 'tempat_lahir' },
                    { data: 'gender', name: 'gender' },
                    { data: 'alamat_asal', name: 'alamat_asal' },
                    { data: 'jalur_pendaftaran', name: 'jalur_pendaftaran' },
                    { data: 'reguler', name: 'reguler' },
                    { data: 'hasil_seleksi', name: 'hasil_seleksi' },

                ]

        });
    });
</script>

@endpush -->