routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');

});

    Route::resource('administrator', 'administratorsController');

    Route::resource('mahasiswa_calons', 'mahasiswa_calonController');
    Route::get('mahasiswa_calon/',['as' => 'mahasiswa_calon', 'uses' => 'mahasiswa_calonController@index']);
    Route::get('mahasiswa_calonCreate/',['as' => 'mahasiswa_calonCreate', 'uses' => 'mahasiswa_calonController@create']);
    //Route::get('get-mahasiswa_calon','mahasiswa_calonController@getmahasiswa_calon');
    

    Route::resource('majors', 'major\majorController');
    Route::get('majorsIndex/',['as' => 'majorsIndex', 'uses' => 'major\majorController@index']);
    Route::get('majorsCreate/',['as' => 'majorsCreate', 'uses' => 'major\majorController@create']);

    Route::resource('faculties', 'faculties\facultiesController');
    Route::get('facultiesIndex/',['as' => 'facultiesIndex', 'uses' => 'faculties\facultiesController@index']);
    Route::get('facultiesCreate/',['as' => 'facultiesCreate', 'uses' => 'faculties\facultiesController@create']);

    Route::resource('departments', 'departments\departmentsController');
    Route::get('departmentsIndex/',['as' => 'departmentsIndex', 'uses' => 'departments\departmentsController@index']);
    Route::get('departmentsCreate/',['as' => 'departmentsCreate', 'uses' => 'departments\departmentsController@create']);

    Route::get('academic_years/',['as' => 'academic_years', 'uses' => 'academic_yearsController@index']);
    Route::get('get-academic_years','academic_yearsController@getacademic_years');

    Route::get('administrators/',['as' => 'administrators', 'uses' => 'administratorsController@index']);
    Route::get('get-administratorsView','administratorsController@getadministrators');
    Route::get('get-administratorsCreate','administratorsController@create');
    Route::get('administratorsCreate/',['as' => 'administratorsCreate', 'uses' => 'administratorsController@create']);
    Route::get('administratorsStore/',['as' => 'administratorsStore', 'uses' => 'administratorsController@store']);

app/majors.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class majors extends Model
{
    protected $table = 'majors';
}

app/Http/Controllers/major/majorController.php
<?php

namespace App\Http\Controllers\major;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\majors;
use App\department;

class majorController extends Controller
{
    public function index()
    {   
        
    	$majors=majors::all();
        return view('majors.majorsView',compact('majors'));
    }
    public function create()
    {
        $departments=department::all();
        return view('majors.majorsCreate',compact('departments'));
        //
    }
    public function store(Request $request)
    {
        $majors = new majors();
        $majors->department_id = $request->department_id;
        $majors->name=$request->name;
        $majors->telp=$request->telp;
        $majors->email=$request->email;
        $majors->address=$request->address;
        $majors->facsimile=$request->facsimile;
        $majors->homepage=$request->homepage;
        $majors->save();
        return redirect()->route('majors.index')->with('alert-success','Data berhasil Disimpan.');
    }
    public function edit($id)
    {
        $departments=department::all();
        $majors = majors::findOrFail($id);
        return view('majors.majorsEdit', compact('departments','majors'));
    }
    public function update(Request $request, $id)
    {
        $majors = majors::findOrFail($id);
        $majors->department_id = $request->department_id;
        $majors->name=$request->name;
        $majors->telp=$request->telp;
        $majors->email=$request->email;
        $majors->address=$request->address;
        $majors->facsimile=$request->facsimile;
        $majors->homepage=$request->homepage;
        $majors->save();
        return redirect()->route('majors.index')->with('alert-success', 'Data Successfully Updated.');
    }
    public function destroy($id)
    {
        $majors = majors::findOrFail($id);
        $majors->delete();
        return redirect()->route('majors.index')->with('alert-success', 'Data Berhasil Dihapus.');
    }
}

resources/views/majors/majorsCreate.blade.php
@extends('index')

@section('content')
<div class="container-fluid">
    
                <div class="panel-body">
                <br style="clear:both">
                    <h4 class="w3-label w3-text-green" style="margin-bottom: 25px; text-align: center;"><b>EDIT JOBLIST</b></h4>
                    <hr>
            <form action="{{route('majors.store')}}" method="post">
                    {{csrf_field()}}
                    <label class="w3-label w3-text-green"><b>Department</b></label>
                        <div class="form-group{{ $errors->has('department_id') ? ' has-error' : '' }}">
                        <select class="form-control m-bot15" name="department_id">
                            @if($departments->count() > 0)
                            @foreach($departments as $department)
                            <option value="{{$department->id}}">{{$department->name}}</option>
                            @endForeach
                            @else
                            No Record Found
                            @endif   
                        </select>
                    </div>
                        <label class="w3-label w3-text-green"><b>name</b></label>
                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <input type="text" name="name" class="form-control" placeholder="name" required>
                        
                            {!! $errors->first('name', '<p class="help-block">:message</p>') !!}
                        </div>
                        <label class="w3-label w3-text-green"><b>Telp</b></label>
                        <div class="form-group{{ $errors->has('telp') ? ' has-error' : '' }}">
                            <input type="text" name="telp" class="form-control" placeholder="telp" required>
                        
                            {!! $errors->first('telp', '<p class="help-block">:message</p>') !!}
                        </div>
                        <label class="w3-label w3-text-green"><b>Email</b></label>
                            <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <input type="email" name="email" class="form-control" placeholder="email" required>
                        
                            {!! $errors->first('email', '<p class="help-block">:message</p>') !!}
                        </div>
                        
                        <label class="w3-label w3-text-green"><b>Address</b></label>
                        <div class="form-group{{ $errors->has('address') ? ' has-error' : '' }}">
                            <input type="text" name="address" class="form-control" placeholder="address" required>
                        
                            {!! $errors->first('address', '<p class="help-block">:message</p>') !!}
                        </div>
                        <label class="w3-label w3-text-green"><b>Facsimile</b></label>
                        <div class="form-group{{ $errors->has('facsimile') ? ' has-error' : '' }}">
                            <input type="text" name="facsimile" class="form-control" placeholder="facsimile" required>
                        
                            {!! $errors->first('facsimile', '<p class="help-block">:message</p>') !!}
                        </div>
                        <label class="w3-label w3-text-green"><b>Homepage</b></label>
                        <div class="form-group{{ $errors->has('homepage') ? ' has-error' : '' }}">
                            <input type="text" name="homepage" class="form-control" placeholder="homepage" required>
                        
                            {!! $errors->first('homepage', '<p class="help-block">:message</p>') !!}
                        </div>
                        
                            <input type="submit" class="btn btn-primary" value="Simpan">
                       

                    </form>
         </div>
     </div>

        <!-- /.content -->
    </section>
    <!-- /.main-section -->
@endsection

resources/views/majors/majorsEdit.blade.php
@extends('index')
@section('content')
<div class="container-fluid">
	
				<div class="panel-body">
				<br style="clear:both">
					<h4 class="w3-label w3-text-green" style="margin-bottom: 25px; text-align: center;"><b>EDIT JOBLIST</b></h4>
                    <hr>
					<form action="{{route('majors.update',$majors->id)}}" method="post">
					<input name="_method" type="hidden" value="PATCH">
					{{csrf_field()}}
						<label class="w3-label w3-text-green"><b>Departement ID</b></label>
						<div class="form-group{{ $errors->has('department_id') ? ' has-error' : '' }}">
							
					<select class="form-control m-bot15" name="department_id">
                            @foreach($departments as $department)
                            <option 
                            value="{{$department->id}}"
                            @if($department->id === $majors->department_id)
                            selected
                            @endif
                            >
                            {{$department->name}}
                        </option>
                            @endForeach
                           
                        </select>

						</div>
						<label class="w3-label w3-text-green"><b>Nama</b></label>
						<div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
							<input type="text" name="name" class="form-control" placeholder="name" value="{{$majors->name}}" required>
							{!! $errors->first('nama', '<p class="help-block">:message</p>') !!}
						</div>

						<label class="w3-label w3-text-green"><b>Telp</b></label>
						<div class="form-group{{ $errors->has('telp') ? ' has-error' : '' }}">
							<input type="text" name="telp" class="form-control" placeholder="Telp" value="{{$majors->telp}}" required>
							{!! $errors->first('telp', '<p class="help-block">:message</p>') !!}
						</div>
						<label class="w3-label w3-text-green"><b>Email</b></label>
						<div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
							<input type="email" name="email" class="form-control" placeholder="Email" value="{{$majors->email}}" required>
							{!! $errors->first('email', '<p class="help-block">:message</p>') !!}
						</div>
						<label class="w3-label w3-text-green"><b>Address</b></label>
						<div class="form-group{{ $errors->has('address') ? ' has-error' : '' }}">
							<input type="text" name="address" class="form-control" placeholder="address" value="{{$majors->address}}" required>
							{!! $errors->first('address', '<p class="help-block">:message</p>') !!}
						</div>
						<label class="w3-label w3-text-green"><b>Facsimile</b></label>
						<div class="form-group{{ $errors->has('facsimile') ? ' has-error' : '' }}">
							<input type="text" name="facsimile" class="form-control" placeholder="Alamat Asal" value="{{$majors->facsimile}}" required>
							{!! $errors->first('facsimile', '<p class="help-block">:message</p>') !!}
						</div>
						<label class="w3-label w3-text-green"><b>Homepage</b></label>
						<div class="form-group{{ $errors->has('homepage') ? ' has-error' : '' }}">
							<input type="text" name="homepage" class="form-control" placeholder="Jalur Pendaftaran" value="{{$majors->homepage}}" required>
							{!! $errors->first('homepage', '<p class="help-block">:message</p>') !!}
						</div>
						<div class="form-group">
							<button type="submit" class="btn button btn-primary pull-right"><span class="glyphicon glyphicon-pencil">Edit</span></button>

							<a href="{{route('majors.index')}}" class="btn button  btn-primary pull-left"><span class="glyphicon glyphicon-arrow-left"></span></a>
						</div>
					</form>
				
		
	</div>
</div>
@endsection

resources/views/majors/majorsView.blade.php
@extends('index')
 
@section('content')
<div class="row">
<div class="col-md-8 col-md-offset-2">
    <h3 align="center">Data Calon Mahasiswa </h3>   
    <a href="{{route('majorsCreate')}}" class="btn btn-primary btn-md" ><span  class="glyphicon glyphicon-list-alt"></span>  Add New</a></a>  
    <div>
        <h3> </h3>
    </div>
    <table class="table table-striped" id="table">
        <thead>
            <tr>
                <td>No</td>
                <td>Departemen ID</td>
                <td>Name</td>
                <td>Telp</td>
                <td>Email</td>
                <td>Address</td>
                <td>Facsimile</td>
                <td>Homepage</td>
                <td>Aksi</td>
                
            </tr>
        </thead>
        <tbody>
            <?php $no=1; ?>
                        @foreach($majors as $data)
                            <tr class="">
                            <td>{{$no++}}</td>
                            <td>{{$data->department_id}}</td>
                            <td>{{$data->name}}</td>
                            <td>{{$data->telp}}</td>
                            <td>{{$data->email}}</td> 
                            <td>{{$data->address}}</td>
                            <td>{{$data->facsimile}}</td>  
                            <td>{{$data->homepage}}</td>   
                            <td><form method="POST" action="{{ route('majors.destroy', $data->id) }}" accept-charset="UTF-8">
                                <input name="_method" type="hidden" value="DELETE">
                                <input name="_token" type="hidden" value="{{ csrf_token() }}">

                                <a href="{{route('majors.edit', $data->id)}}" class="btn btn-primary btn-xs" data-toggle="tooltip" data-placement="bottom" title="edit"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>


                                <button type="submit" class="btn btn-primary btn-xs" data-toggle="tooltip" data-placement="bottom" title="delete"><span class="glyphicon glyphicon-trash" onclick="return confirm('Anda yakin akan menghapus data ?');" ></span>
                                    </button>
                                </form>
                            </td>
                            </tr>
                            @endforeach
        </tbody>
    </table>
</div>
</div>
@endsection