routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');

});

    Route::resource('administrator', 'administratorsController');

    Route::resource('mahasiswa_calons', 'mahasiswa_calonController');
    Route::get('mahasiswa_calon/',['as' => 'mahasiswa_calon', 'uses' => 'mahasiswa_calonController@index']);
    Route::get('mahasiswa_calonCreate/',['as' => 'mahasiswa_calonCreate', 'uses' => 'mahasiswa_calonController@create']);
    //Route::get('get-mahasiswa_calon','mahasiswa_calonController@getmahasiswa_calon');
    

    Route::resource('majors', 'major\majorController');
    Route::get('majorsIndex/',['as' => 'majorsIndex', 'uses' => 'major\majorController@index']);
    Route::get('majorsCreate/',['as' => 'majorsCreate', 'uses' => 'major\majorController@create']);

    Route::resource('faculties', 'faculties\facultiesController');
    Route::get('facultiesIndex/',['as' => 'facultiesIndex', 'uses' => 'faculties\facultiesController@index']);
    Route::get('facultiesCreate/',['as' => 'facultiesCreate', 'uses' => 'faculties\facultiesController@create']);

    Route::resource('departments', 'departments\departmentsController');
    Route::get('departmentsIndex/',['as' => 'departmentsIndex', 'uses' => 'departments\departmentsController@index']);
    Route::get('departmentsCreate/',['as' => 'departmentsCreate', 'uses' => 'departments\departmentsController@create']);

    Route::get('academic_years/',['as' => 'academic_years', 'uses' => 'academic_yearsController@index']);
    Route::get('get-academic_years','academic_yearsController@getacademic_years');

    Route::get('administrators/',['as' => 'administrators', 'uses' => 'administratorsController@index']);
    Route::get('get-administratorsView','administratorsController@getadministrators');
    Route::get('get-administratorsCreate','administratorsController@create');
    Route::get('administratorsCreate/',['as' => 'administratorsCreate', 'uses' => 'administratorsController@create']);
    Route::get('administratorsStore/',['as' => 'administratorsStore', 'uses' => 'administratorsController@store']);

app/Http/Controllers/faculties/facultiesController.php
<?php

namespace App\Http\Controllers\faculties;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\faculties;
use App\kota_kabupaten;

class facultiesController extends Controller
{
    public function index()
    {   
        
    	$faculties=faculties::all();
        return view('faculties.facultiesView',compact('faculties'));
    }
    public function create()
    {
    	$kota_kabupaten=kota_kabupaten::all();
        return view('faculties.facultiesCreate',compact('kota_kabupaten'));
    }
    public function store(Request $request)
    {
        $faculties = new faculties();
        $faculties->name=$request->name;
        $faculties->university=$request->university;
        $faculties->telp=$request->telp;
        $faculties->email=$request->email;
        $faculties->founded_on=$request->founded_on;
        $faculties->city=$request->city;
        $faculties->save();
        return redirect()->route('faculties.index')->with('alert-success','Data berhasil Disimpan.');
    }
    public function edit($id)
    {
        $kota_kabupaten=kota_kabupaten::all();
        $faculties = faculties::findOrFail($id);
        return view('faculties.facultiesEdit', compact('kota_kabupaten','faculties'));
    }
    public function update(Request $request, $id)
    {
        $faculties = faculties::findOrFail($id);
        $faculties->name=$request->name;
        $faculties->university=$request->university;
        $faculties->telp=$request->telp;
        $faculties->email=$request->email;
        $faculties->founded_on=$request->founded_on;
        $faculties->city=$request->city;
        $faculties->save();
        return redirect()->route('faculties.index')->with('alert-success', 'Data Successfully Updated.');
    }
    public function destroy($id)
    {
        $faculties = faculties::findOrFail($id);
        $faculties->delete();
        return redirect()->route('faculties.index')->with('alert-success', 'Data Berhasil Dihapus.');
    }
}

resources/views/faculties/facultiesCreate.blade.php
@extends('index')

@section('content')
<div class="container-fluid">
    
                <div class="panel-body">
                <br style="clear:both">
                    <h4 class="w3-label w3-text-green" style="margin-bottom: 25px; text-align: center;"><b>Tambah Fakultas</b></h4>
                    <hr>
            <form action="{{route('faculties.store')}}" method="post">
                    {{csrf_field()}}
                        <label class="w3-label w3-text-green"><b>name</b></label>
                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <input type="text" name="name" class="form-control" placeholder="name" required>
                        
                            {!! $errors->first('name', '<p class="help-block">:message</p>') !!}
                        </div>
                        <label class="w3-label w3-text-green"><b>University</b></label>
                        <div class="form-group{{ $errors->has('university') ? ' has-error' : '' }}">
                            <input type="text" name="university" class="form-control" placeholder="university" required>
                        
                            {!! $errors->first('university', '<p class="help-block">:message</p>') !!}
                        </div>
                        <label class="w3-label w3-text-green"><b>Telp</b></label>
                            <div class="form-group{{ $errors->has('telp') ? ' has-error' : '' }}">
                            <input type="telp" name="telp" class="form-control" placeholder="telp" required>
                        
                            {!! $errors->first('telp', '<p class="help-block">:message</p>') !!}
                        </div>
                        
                        <label class="w3-label w3-text-green"><b>Email</b></label>
                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <input type="email" name="email" class="form-control" placeholder="email" required>
                        
                            {!! $errors->first('email', '<p class="help-block">:message</p>') !!}
                        </div>
                        <label class="w3-label w3-text-green"><b>Founded On</b></label>
                        <div class="form-group{{ $errors->has('founded_on') ? ' has-error' : '' }}">
                            <input type="date" name="founded_on" class="form-control" placeholder="founded_on" required>
                        
                            {!! $errors->first('founded_on', '<p class="help-block">:message</p>') !!}
                        </div>
                        <label class="w3-label w3-text-green"><b>City</b></label>
                        <div class="form-group{{ $errors->has('homepage') ? ' has-error' : '' }}">
                            <select class="form-control m-bot15" name="city">
                            @if($kota_kabupaten->count() > 0)
                            @foreach($kota_kabupaten as $kota)
                            <option value="{{$kota->id}}">{{$kota->nama_kota_kabupaten}}</option>
                            @endForeach
                            @else
                            No Record Found
                            @endif   
                        </select>
                        </div>
                        
                            <input type="submit" class="btn btn-primary" value="Simpan">
                       

                    </form>
         </div>
     </div>

        <!-- /.content -->
    </section>
    <!-- /.main-section -->
@endsection

resources/views/faculties/facultiesEdit.blade.php
@extends('index')
@section('content')
<div class="container-fluid">
	
				<div class="panel-body">
				<br style="clear:both">
					<h4 class="w3-label w3-text-green" style="margin-bottom: 25px; text-align: center;"><b>EDIT JOBLIST</b></h4>
                    <hr>
					<form action="{{route('faculties.update',$faculties->id)}}" method="post">
					<input name="_method" type="hidden" value="PATCH">
					{{csrf_field()}}
						<label class="w3-label w3-text-green"><b>Nama</b></label>
						<div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
							<input type="text" name="name" class="form-control" placeholder="name" value="{{$faculties->name}}" required>
							{!! $errors->first('nama', '<p class="help-block">:message</p>') !!}
						</div>
						<label class="w3-label w3-text-green"><b>University</b></label>
						<div class="form-group{{ $errors->has('university') ? ' has-error' : '' }}">
							<input type="text" name="university" class="form-control" placeholder="Jalur Pendaftaran" value="{{$faculties->university}}" required>
							{!! $errors->first('university', '<p class="help-block">:message</p>') !!}
						</div>
						<label class="w3-label w3-text-green"><b>Telp</b></label>
						<div class="form-group{{ $errors->has('telp') ? ' has-error' : '' }}">
							<input type="text" name="telp" class="form-control" placeholder="Telp" value="{{$faculties->telp}}" required>
							{!! $errors->first('telp', '<p class="help-block">:message</p>') !!}
						</div>
						<label class="w3-label w3-text-green"><b>Email</b></label>
						<div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
							<input type="email" name="email" class="form-control" placeholder="Email" value="{{$faculties->email}}" required>
							{!! $errors->first('email', '<p class="help-block">:message</p>') !!}
						</div>
						<label class="w3-label w3-text-green"><b>Founded On</b></label>
						<div class="form-group{{ $errors->has('founded_on') ? ' has-error' : '' }}">
							<input type="date" name="founded_on" class="form-control" placeholder="Alamat Asal" value="{{$faculties->founded_on}}" required>
							{!! $errors->first('founded_on', '<p class="help-block">:message</p>') !!}
						</div>
						
						<label class="w3-label w3-text-green"><b>City</b></label>
						<div class="form-group{{ $errors->has('address') ? ' has-error' : '' }}">
							<select class="form-control m-bot15" name="city">
                            @foreach($kota_kabupaten as $major)
                            <option 
                            value="{{$major->id}}"
                            @if($major->id === $faculties->city)
                            selected
                            @endif
                            >
                            {{$major->nama_kota_kabupaten}}
                        </option>
                            @endForeach
                           
                        </select>
							{!! $errors->first('city', '<p class="help-block">:message</p>') !!}
						</div>
						
						<div class="form-group">
							<button type="submit" class="btn button btn-primary pull-right"><span class="glyphicon glyphicon-pencil">Edit</span></button>

							<a href="{{route('faculties.index')}}" class="btn button  btn-primary pull-left"><span class="glyphicon glyphicon-arrow-left"></span></a>
						</div>
					</form>
				
		
	</div>
</div>
@endsection

resources/views/faculties/facultiesView.blade.php
@extends('index')
 
@section('content')
<div class="row">
<div class="col-md-8 col-md-offset-2">
    <h3 align="center">Data Calon Mahasiswa </h3>   
    <a href="{{route('facultiesCreate')}}" class="btn btn-primary btn-md" ><span  class="glyphicon glyphicon-list-alt"></span>  Add New</a></a>  
    <div>
        <h3> </h3>
    </div>
    <table class="table table-striped" id="table">
        <thead>
            <tr>
                <td>No</td>
                <td>Name</td>
                <td>University</td>
                <td>Telp</td>
                <td>Email</td>
                <td>Founded On</td>
                <td>City</td>
                <td>Aksi</td>
                
            </tr>
        </thead>
        <tbody>
            <?php $no=1; ?>
                        @foreach($faculties as $data)
                            <tr class="">
                            <td>{{$no++}}</td>
                            <td>{{$data->name}}</td>
                            <td>{{$data->university}}</td>
                            <td>{{$data->telp}}</td> 
                            <td>{{$data->email}}</td>
                            <td>{{$data->founded_on}}</td>  
                            <td>{{$data->city}}</td>   
                            <td><form method="POST" action="{{ route('faculties.destroy', $data->id) }}" accept-charset="UTF-8">
                                <input name="_method" type="hidden" value="DELETE">
                                <input name="_token" type="hidden" value="{{ csrf_token() }}">

                                <a href="{{ route('faculties.edit', $data->id) }}" class="btn btn-primary btn-xs" data-toggle="tooltip" data-placement="bottom" title="edit"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>


                                <button type="submit" class="btn btn-primary btn-xs" data-toggle="tooltip" data-placement="bottom" title="delete"><span class="glyphicon glyphicon-trash" onclick="return confirm('Anda yakin akan menghapus data ?');" ></span>
                                    </button>
                                </form>
                            </td>
                            </tr>
                            @endforeach
        </tbody>
    </table>
</div>
</div>
@endsection